### PR TITLE
Add some sample json data

### PR DESCRIPTION
**Pull request by alicak**
Generated with [http://www.mockaroo.com/](url).

### CODE REVIEW

**Comment by marvec** [comment]
Almost, please note the new file format. Currently, it won't work, there needs to be a prefix in the files. See https://github.com/Lumeer/engine/tree/devel/utils/src/test/resources What you need is array-json.

**Comment by marvec** [comment]
Was it intentional to reduce the number of records significantly?

**Comment by alicak** [comment]
Yes. As I was researching competition, I saw some of their sample data and they did not use so much records - they rather use more tables that are more targeted on some purpose. I plan to do the same with our sample data in future.

**Comment by livthomas** [comment]
Please, be aware of the latest changes in the REST API URLs (https://github.com/Lumeer/engine/commit/c2a32339e5c9bab91f061e87fee7c528f228fcb0).

**Comment by marvec** [comment]
So are we fine to merge?

**Review by livthomas — CHANGES_REQUESTED** [review]
The paths need to be fixed. Otherwise, it will not work after the latest changes in the REST URLs.

**Review by livthomas — APPROVED** [review]

**Pull request merged**
